language: python
python:
- 3.7
before_install:
- pip install poetry
install:
- poetry install
script:
- make build-docker
- poetry run black --check hossler_website tests
- poetry run pytest
deploy:
  provider: script
  script: bash docker_push.sh
  skip_leanup: true
  on:
    branch: master
