language: python
python:
- 3.7
before_install:
- pip install poetry
install:
- poetry install
script:
- poetry run black --check hossler_website tests
- poetry run pytest
- make build-docker
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
