language: python
python:
- 3.7
before_install:
- pip install poetry
- bash get_kube_config.sh
install:
- poetry install
script:
- make build-docker
- poetry run black --check hossler_website tests
- poetry run pytest
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
